spring.application.name=urlShortner

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=Laksh
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
